# Generated by Django 3.2.7 on 2025-12-27 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploads',
            name='file',
        ),
        migrations.AddField(
            model_name='uploads',
            name='data',
            field=models.TextField(default={'abc': 2}),
            preserve_default=False,
        ),
    ]
