# Generated by Django 3.2.7 on 2025-12-27 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0002_auto_20251227_1046'),
    ]

    operations = [
        migrations.CreateModel(
            name='staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=150)),
                ('department', models.CharField(default='Fraud Review', max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='uploads',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploads',
            name='reviewed_by',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='uploads',
            name='staff_review',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploads',
            name='status',
            field=models.CharField(default='pending', max_length=150),
        ),
    ]
